# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      
      New-Item C:\temp\test.html
      
      Set-Content C:\temp\test.html '<!DOCTYPE html>
      <html>
      <body>
      
      <h1>My First Heading</h1>
      <p>My first paragraph.</p>
      
      </body>
      </html>'

- task: PublishHtmlReport@1
  inputs:
    reportDir: 'C:\temp\test.html'



